### PR TITLE
Optimized the logic of the MinIO avatar and added the data statistics API

### PR DESCRIPTION
**Pull request by WanAnUncommon**
- Implement MinIO linkage with MySQL database to save the avatar file name
- Add a data statistics API
   -  Count the total number of people
   - Statistics on the number of men or women
   - Statistics on the number of people on each province

### CODE REVIEW

**Comment by JackLau1222** [comment]
Please delete your git file(.gitignore) and executable files like .jar and some unuseful files,please check and fix it,Thanks!

**Comment by 1418875140** [comment]
I have carefully reviewed the overall project code and would like to provide some feedback.

Firstly, I think the code for the controller layer is too complex. We should try to concentrate the code on the service layer as much as possible. According to the Alibaba Java Development Manual, the purpose of the controller layer is to provide parameters for the service layer. For example, obtaining the user ID here can pass in the method called by the service.

Secondly, too much if nesting can lead to poor code readability. I think we can use AOP to reduce the frequent occurrence of code that determines whether to log in or whether parameters are empty. Also, I found some code where you check whether the parameters are empty in the controller layer, but repeat the check in the service layer, which makes the code very messy.

Then I found out that you used a lot of data desensitization and even encapsulated some methods. According to the specifications, you should create new VO objects to display the view, instead of using a lot of original classes to display it.

There are also some minor issues, such as not putting MinIOProperty in the entity package, which is not in compliance with regulations and should be placed in the config package. Another thing is that you can actually use a lot of packaged toolkits, such as the BeanUtil. copyPropertys() method, but you need to manually package parameters one by one (from the hutool tool class). There is also a naming convention similar to UserContent, which should be UserConstant. Also, don't you think it's cumbersome to manually determine exceptions and throw them every time you add, delete, or modify a query? For example, with the addAnnouncement method, you can actually implement a global exception handling class to handle these exceptions uniformly. We don't need to worry about perfect prompts such as "failed announcement addition" and "failed user addition", In fact, a "system error" can also let users know their problem! At present, these issues have been discovered. You can follow the Alibaba Java Development Manual or make modifications according to some projects. You can also check out some blogs on CSDN, which discuss the differences between the three-layer architecture and VO, DTO, and PO in Java. This will also improve your code habits.

**Comment by WanAnUncommon** [comment]
I have done some code formatting optimizations,please help me check it out.

**Comment by WanAnUncommon** [comment]
I am back again !

**Comment by 1418875140** [comment]
> I am back again !

Good Job！There are some suggestions for you when we go to school

**Comment by WanAnUncommon** [comment]
I am back again !

**Comment by 1418875140** [comment]
> I am back again !

Well done! But don't submit some compiled files to it. If possible, you can change the example package name to OSC to make it more formal.And it seems that you haven't completed some of the documents in the resource folder

**Comment by WanAnUncommon** [comment]
The basic business logic of the front and back end is implemented.

**Comment by 1418875140** [comment]
On the 26th, I will try to deploy it

**Pull request merged**
